import { Icon, Button, Tabbar, TabbarItem, NavBar, Toast, Swipe, SwipeItem, Search, Grid, GridItem, Rate, ActionSheet, Dialog, Checkbox, CheckboxGroup, AddressList, AddressEdit, Area, Tab, Tabs } from 'vant'
import Vue from 'vue'

Vue.use(Dialog)
Vue.use(Tab)
Vue.use(Tabs)
Vue.use(Area)
Vue.use(AddressEdit)
Vue.use(AddressList)
Vue.use(Checkbox)
Vue.use(CheckboxGroup)
Vue.use(ActionSheet)
Vue.use(Icon)
Vue.use(Rate)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(Search)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Toast)
Vue.use(NavBar)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(Button)
